version: '3'
services:

  selenoid:
    image: "aerokube/selenoid:latest-release"
    container_name: "selenoid"
    restart: "always"
    expose:
      - "4444"
    volumes:
      - "${PWD}/data/config:/etc/selenoid"
      - "${PWD}/data/video:/opt/selenoid/video"
      - "${PWD}/data/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      OVERRIDE_VIDEO_OUTPUT_DIR: "${PWD}/data/video"
    command: ["--container-network", "selenium", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]

  ui:
    image: "aerokube/selenoid-ui"
    container_name: "selenoid-ui"
    restart: "always"
    depends_on:
      - "selenoid"
    expose:
      - "8080"
    command: ["--selenoid-uri", "http://selenoid:4444", "--period", "100ms"]

  proxy:
    image: "mcsim/openresty:base"
    container_name: "selenoid-proxy"
    restart: "always"
    volumes:
      - "${PWD}/conf.d:/etc/nginx/conf.d/templates"
    expose:
      - "80"
    environment:
      - "SELENOID_DOMAIN=selenoid.${DOMAIN_NAME}"
      - "SELENOID_UI_DOMAIN=selenoid-ui.${DOMAIN_NAME}"
    depends_on:
      - "ui"
    labels:
      - "traefik.frontend.rule=Host:selenoid.${DOMAIN_NAME},selenoid-ui.${DOMAIN_NAME}"
    command: /bin/bash -c "envsubst '$${SELENOID_DOMAIN} $${SELENOID_UI_DOMAIN}' < /etc/nginx/conf.d/templates/proxy.template > /etc/nginx/conf.d/default.conf && /usr/local/openresty/bin/openresty -g 'daemon off;'"

networks:
  default:
    external:
      name: selenoid
